### ISSUE TITLE
Plugin name gets translated

### ISSUE THREAD

**Issue by End18Zone** [phpbits/widget-options#1]
Hi this aint much of an issue but a headsup. The plugin name is getting translated to swedish see <a href="http://www.zimagez.com/zimage/screenshot-2016-06-17-201628.php">screenshot</a>

**Comment by phpbits** [comment]
Hi @End18Zone ,

Thank you for reporting the issue. Unfortunately there is no translation available for the plugin as of the moment but will keep you posted. Thanks!

Cheers,
Jeffrey
