### ISSUE TITLE
Allow Display Logic to be disabled with constant

### ISSUE THREAD

**Issue by michaelryanmcneill** [phpbits/widget-options#12]
Because of the potential security risks associated with allowing text to be directly eval'd, it would be great if we could disable "Display Logic" with a `wp-config.php` constant. While I'm currently using the existing filter, `widget_options_logic_override` to disable it, it would be nice to be able to disable it with a constant.

**Comment by phpbits** [comment]
Hi @michaelryanmcneill 

Thank you so much for the suggestion. Will let you know when this functionality has been added. Thanks again!

Cheers,
Jeffrey
