### ISSUE TITLE
PHP 7.1 warnings  

### ISSUE THREAD

**Issue by laxbobber** [phpbits/widget-options#13]
Widget Options Version 3.1 running on PHP 7.1 will generate an error_log with the following:

PHP Warning:  Illegal string offset 'pages' in /home/example/public_html/wp-content/plugins/widget-options/core/functions.widget.display.php on line 241

PHP Warning:  Illegal string offset 'pages' in /home/example/public_html/wp-content/plugins/widget-options/core/functions.widget.display.php on line 243

PHP Warning:  array_key_exists() expects parameter 2 to be array, string given in /home/example/public_html/wp-content/plugins/widget-options/core/functions.widget.display.php on line 243

**Comment by phpbits** [comment]
Hi,

Thank you very much for choosing Widget Options. Regarding your concern, are you using the latest version? Checked the lines with errors : https://github.com/phpbits/widget-options/blob/master/core/functions.widget.display.php and it seems not the issue.  Also, can you go to **Settings > Widget Options** and enable the Page Visibility option. Let me know how it goes. Thanks!

Cheers,
Jeffrey

**Comment by laxbobber** [comment]
Set WP_DEBUG to true in your wp-config.php and use Version 3.1 with PHP 7.1.0 and you'll see it.

It looks like it is because you are initially setting $visibility to an empty string but then later treating it as an array ( with isset( $visibility['pages'] ).

**Comment by phpbits** [comment]
Hi,

Does enabling the page visibility on the settings page fixes the issue? This will do for the meantime while I'm updating the plugin. I hope this is fine with you. Thanks!

Cheers,
Jeffrey

**Comment by phpbits** [comment]
Hi,

Please update to the latest version and let me know when you encounter any issues. Thanks!

Cheers,
Jeffrey

**Comment by laxbobber** [comment]
Did a quick test just now and it is looking good so far! Thank you!

**Comment by phpbits** [comment]
Sounds perfect :) Thanks!
