### ISSUE TITLE
CPTs no longer show in visibility options

### ISSUE THREAD

**Issue by paulovsky** [phpbits/widget-options#14]
Hello 

Recently realized that my custom post types no longer appear on the visibility options.

I am using Toolset Types.

I'm a newb, please advise me on how to troubleshoot or fix this

**Comment by phpbits** [comment]
Hi,

The plugin is tracking the newly added post types after it has any items assigned to it : https://github.com/phpbits/widget-options/blob/master/includes/transient.php . Please add item on custom post type then let me know if it works perfectly. Thanks!

Cheers,
Jeffrey

**Comment by phpbits** [comment]
Hi,

Tested and seems like Toolset Types are not returning on get_post_types() function. Does it work on the previous plugin version? And when did it stop working? After Widget Options update or Toolset Types? Thank you very much!

Cheers,
Jeffrey

**Comment by paulovsky** [comment]
Hi,

Both were updated on the same day; I'm afraid I didn't notice after which update it stopped working.

Thank you

**Comment by phpbits** [comment]
Hi,

You might want to contact the plugin developer. Downloaded Toolset Types too and used `get_post_types` on the theme to check if it will get the defined post types on the plugin but it doesn't. I hope they can enlightened us with this issue. Thanks!

Cheers,
Jeffrey

**Comment by paulovsky** [comment]
Thanks @phpbits , just [did that](https://wordpress.org/support/topic/get_post_types-not-working-after-last-update/). Waiting for a reply.

Thanks for your quick reply

**Comment by phpbits** [comment]
Awesome! Keep me posted. Thanks!

**Comment by phpbits** [comment]
Hi @paulovsky 

Can you please check https://github.com/phpbits/widget-options/tree/develop the update? Tried on my development and seems to fixed the issue. Please do add new post types item to refresh the post type transient set by the plugin. Let me know how it goes. Thanks!

Cheers,
Jeffrey

**Comment by sariha** [comment]
Hi, 
the fixes on branch develop resolved the issue on our installation ;)

**Comment by phpbits** [comment]
Hi @sariha 

Sounds perfect! Will upload the fixes soon! For the meantime please use this dev version. Thanks!

Cheers,
Jeffrey
