### ISSUE TITLE
Add overlay on background-image option (Extended Widget Options)

### ISSUE THREAD

**Issue by diegoleft** [phpbits/widget-options#16]
I'm using the theme "Astrid" that when I add a background-image automatically the theme add an overlay to make dark the image then I can add legible text above.

After installing Widget-options all my widgets with background-image, has disappeared the overlay above the images, making very hard to read the contents.

It's possivel add this functionality when we use a background-image? or how can edit the widget without destroy my changes after an update?

Thanks!

**Comment by phpbits** [comment]
Hi @diegoleft,

Thank you very much for choosing Extended Widget Options! Since you are using the premium version, please create a support ticket here : http://phpbits.net/contact/ with your website link and will be very happy to check your issue. Thanks!

Cheers,
Jeffrey
