### ISSUE TITLE
Import / Export

### ISSUE THREAD

**Issue by exisadmin** [phpbits/widget-options#19]
We suggest that there should be a new feature to export all plugin’s settings. In many of our projects we do have hundreds of widgets and all of them include widget logic. We would very much appreciate to backup these logics. We use “Widget Importer & Exporter”, but this plugin only backups the widgets, without any 3rd party logic on them.

Thumbs up for your great plugin!

**Comment by phpbits** [comment]
@exisadmin This feature has been added and available for public testing on the Develop branch : https://github.com/phpbits/widget-options/tree/develop . Feel free to check and let me know how it goes. 💯 

Cheers,
Jeffrey

**Comment by exisadmin** [comment]
thumbs up!

**Comment by phpbits** [comment]
Thank you very much @exisadmin . Have encountered any issues when you tried it? There are more ways to back up widgets using Widget Options :) 

https://youtu.be/t93QZxzpStY

https://youtu.be/Fvx3nVgOH2w

Cheers,
Jeffrey
