### ISSUE TITLE
Suggestion: visibility for post type archive

### ISSUE THREAD

**Issue by paulwilde** [phpbits/widget-options#2]
Love the plugin.

Just a quick suggestion: It would be nice if you added the option to filter the visibility of post type archives. Currently there is the option for "Archives" but that covers every archive.

A use case is to show sidebar widgets for a certain custom post type, such as WooCommerce.

Thanks

**Comment by phpbits** [comment]
Hi @paulwilde ,

Thank you so much! I'm really glad that you love the plugin, currently the post type taxonomies are supported only on the [extended version](https://phpbits.net/plugin/extended-widget-options/). Thanks again!

Cheers,
phpbits
