### ISSUE TITLE
Indent child pages

### ISSUE THREAD

**Issue by KevinBatdorf** [phpbits/widget-options#21]
Would be very useful to me if you could indent and organize pages not alphabetically but by page and sub pages. Thanks

**Comment by phpbits** [comment]
Hi,

Thank you very much for your suggestion :)

Cheers,
Jeffrey

**Comment by phpbits** [comment]
Hi @KevinBatdorf 

I've added this enhancement on the next updates. It's already available for testing on the development version : https://github.com/phpbits/widget-options/tree/develop . I hope you'll give it a try and let me know your thoughts. Thanks!

Cheers,
Jeffrey

**Comment by KevinBatdorf** [comment]
Awesome, I'll check it out on he next project I have (in a few weeks though)! Salamat

**Comment by phpbits** [comment]
You are very welcome @KevinBatdorf! I've added more features that would be very helpful on your development too. You can now Import & Export widgets of create per widget area back up ;) and more. I hope you'll love this features too! Also available for free and on that development version. Planning to release them this month. Hoping for your feedbacks. Cheers!

https://youtu.be/t93QZxzpStY

https://youtu.be/Fvx3nVgOH2w
