### ISSUE TITLE
Destroyed

### ISSUE THREAD

**Issue by sorna8325** [phpbits/widget-options#24]
When I updated widget options.my theme get problem.I need previous version.please give me link of previous version.I search any where

**Comment by phpbits** [comment]
Hi,

Thank you very much for contacting me regarding your issue. Can you send screenshots of what happened? If you can include your website link that would be of great help to fix the issue rather than downgrading. Thank you very much for your understanding.

Regards,
Jeffrey

**Comment by sorna8325** [comment]
Hi,
Https://jidi.ir it's my website. In first page you can see problem.distance box of content on left and right. Theme at first it was like this.but I add cuss and remove the distance in left and right. Second problem is widget on footer. Background and title is changed. 
Thanks for helping me.

**Comment by phpbits** [comment]
Hi,

Thank you very much! Just checked and it seems that the theme you are using wasn't adding the default 'widget' class, in which the plugin does and conflicting with the theme's stylesheet. You can edit your plugin copy and on this file : https://github.com/phpbits/widget-options/blob/master/includes/widgets/display.php comment out line 325. Will probably add hook on the next release to avoid editing this file. Let me know how it goes. Thanks!

Cheers,
Jeffrey

**Comment by sorna8325** [comment]
hi,
edited tha file with your code but dont changed any thing. still on footer back ground is changed and content box in lef an right  have extra space.

**Comment by phpbits** [comment]
Hi,

You need to clear the website cache if you are using any caching plugin and it will work just fine :) Thanks!

Cheers,
Jeffrey

**Comment by sorna8325** [comment]
hi, thank you but
i cached and not changed any thing.

**Comment by phpbits** [comment]
Hi @sorna8325 ,

Have you tried deactivating the plugin and checked if the issue still exists? It's probably from other plugin you are using. Does the previous version works perfectly on your end? Thanks!

**Comment by sorna8325** [comment]
hi,
yes when i deactivating the plugin evry thing is ok. and yes previous version works perfectly on my website. please just give me previous version. 
thanks so much

**Comment by sorna8325** [comment]
hi, 
so  you can not give me previous version?

**Comment by phpbits** [comment]
Hi,

My apology for late response. For some reason, I didn't get notified. If the previous version is working perfectly on your site. You can use this one :
[widget-options.zip](https://github.com/phpbits/widget-options/files/1213824/widget-options.10.zip)

Let me know how it goes. Thanks!

Cheers,
Jeffrey
