### ISSUE TITLE
Problem theme

### ISSUE THREAD

**Issue by sorna8325** [phpbits/widget-options#25]
Hi, thank you too,
Https://jidi.ir it's my website. In first page you can see problem.distance box of content on left and right. Theme at first it was like this.but I add css and remove the distance in left and right. this problem in mobile its so bad. Second problem is widget on footer. Background and title is changed. when disable plugin problem become fix. but i need this plugin.
Thanks for helping me.
Comment on issue
 
Leave a comment
Close issue   Comment
Notifications for this thread
You’re receiving notifications because you authored the thread.

  Unsubscribe
 Desktop version

**Comment by phpbits** [comment]
Closing this one since it's same here : https://github.com/phpbits/widget-options/issues/25 . Thank you very much!
