### ISSUE TITLE
Not show on WooCommerce Shop page.

### ISSUE THREAD

**Issue by MennStudio** [phpbits/widget-options#28]
Thank you for your great product.

I've tried and found that - if I set the widget to show on WooCommerce's Shop page, it's not working.

## How to reproduce?

Use any theme (This is Twenty Seventeen) and choose **Show on checked pages**. I choose "**Shop**" page and also "**Product**" post type.

![screenshot 2017-08-20 10 41 16](https://user-images.githubusercontent.com/4017086/29491891-237713ea-8594-11e7-8749-ec8e8fba62f8.png)

Please advise,

Thank you so much.

**Comment by phpbits** [comment]
Hi,

Thank you very much for choosing Widget Options! The plugin doesn't fully support WooCommerce conditional statement as of the moment. For **Shop Page** please use the Display Widget Logic option for now and use `is_shop()`

Let me know how it goes. Thanks!

Cheers,
Jeffrey

**Comment by MennStudio** [comment]
Oh, thank you so much. Sorry I forgot this option.

Now I can make it work. But on Visibility Tab -> Hide/Show - I have to select "Hide on checked pages". Then the logic is active.

Cheers,
Menn

**Comment by phpbits** [comment]
Hi,

You are very welcome! Can you try `is_shop() || is_product()` . Let me know how it goes. Thanks!

Cheers,
Jeffrey
