### ISSUE TITLE
Suggestion to import 'Display widgets' settings

### ISSUE THREAD

**Issue by eggdesign** [phpbits/widget-options#29]
Great plugin. Just a suggestion - now that the plugin "display Widgets" has been defunct due to recent spamming issues, it might be a good idea to add a "import settings from display widgets" option in your plugin? It would really help people who have that plugin installed on loads of sites & need to replace it with this plugin

**Comment by phpbits** [comment]
@eggdesign Thank you very much for the suggestion! I'm actually thinking about that. I'll probably just create a separate plugin that can be deactivated after import. Will keep you posted. Thanks!

Cheers,
Jeffrey

**Comment by eggdesign** [comment]
Cool! That would really help. I had the misfortune of installing that damn plugin on all my sites :(

**Comment by phpbits** [comment]
@eggdesign :( please do scan your database too. There's probably inserted data, also check wp-uploads, some user reported that Display Widgets created a folder there.

**Comment by eggdesign** [comment]
cheers will do!

**Comment by phpbits** [comment]
@eggdesign Done with the migration tool :) You can download it here : https://github.com/phpbits/widget-options-migrator . Please do backup your site first or use staging version of your site to make sure that all are working perfectly and don't have any conflicts with any of your plugins. Thanks again for choosing Widget Options and I hope you are loving the plugin features.

https://www.youtube.com/watch?v=qZjvVH6F-FU

Cheers!

**Comment by eggdesign** [comment]
Wow thanks dude! Thats super. Ill test it out today :)

**Comment by phpbits** [comment]
@eggdesign You are very welcome :) Let me know how it goes. I hope you'll love the plugin's features. 

Cheers!

**Comment by phpbits** [comment]
@eggdesign how's the migrator doing :) Let me know if in any case you encounter any issues. Thanks!

**Comment by eggdesign** [comment]
All going good so far! Ive successfully migrated 3 sites already, ill let you know if any issues. Thanks again! :)

**Comment by phpbits** [comment]
@eggdesign Perfect! Will close this ticket now :) Just create a follow up just in case you encounter any issues. I hope you are loving Widget Options' features :)
