### ISSUE TITLE
On/Off switch for plugin

### ISSUE THREAD

**Issue by erpol** [phpbits/widget-options#33]
This is a usability suggestion: 
As the options appear on every widget whether they're used or not, for sites with lots of widgets and complex placements, it's fastidious when maintaining the site to scroll through all the visibility pages and other options to see which, if any, has been checked, or any CSS or logic entered. 

So I'd suggest putting a checkbox on top, to globally enable or disable widget options. 
This would make it very easy to check out if any option has been entered (box checked), at a single glance, before starting scrollling down for specific pages or the various tabs.

**Comment by phpbits** [comment]
@erpol Thank you very much for your suggestions! Do you mean check/uncheck all checkbox feature? or reset default? Thanks!

Cheers,
Jeffrey

**Comment by erpol** [comment]
Hi, you're welcome.

No, I didn't mean reset the defaults, I meant enable/disable globally the various settings the user might have made to the options extensions, while keeping them if they did any changes.
The check box that could be labeled < Enable options > or some similar, off by default, would have the following advantages:
- Remove the ambiguity of < Hide on selected >, which means nothing is done if nothing is checked
- see at a single glance if any options are set: box unchecked means no options active, even if set.
- be able to verify very easily the effect of the settings you have made, without undoing everything, by just unchecking the box.

I often wished for this feature when using Display Widgets, when you visit back a site that you work on periodically it's very tedious to check every widget to see if any changes were made (especially if the default < hide on selected > is kept.)

Sorry this is a bit long, but I'm trying to be as clear as possible!

Thanks for being so reactive, it gives a lot of confidence in your plugin!

RP

Le 21 nov. 2017 ? 08:08, Jeffrey Carandang <notifications@github.com<mailto:notifications@github.com>> a ?crit :


@erpol<https://github.com/erpol> Thank you very much for your suggestions! Do you mean check/uncheck all checkbox feature? or reset default? Thanks!

Cheers,
Jeffrey

-

**Comment by phpbits** [comment]
@erpol You are very welcome! I really do appreciate your suggestions too.

I'm still confuse on the features you need though. The Enable/Disable feature is already available on **Settings Widget Options** and you can configure settings to select which tabs you want to enable. Let me know your thoughts. Thanks!

**Comment by erpol** [comment]
Ok, i understand the confusion: I meant an on/off switch on top of the widget options area of EVERY widget. I can send you a mock screenshot if you wish. 

RP

**Comment by erpol** [comment]
Hi again,

Here, look at the attached mock-up screen to see exactly what I mean (a picture equals 1000 words, etc):


-          On the left, the default state: The box in unchecked, the options are hidden: no clutter
If you don’t need anything specific on a widget, leave unchecked.

-          On the right, as soon as you check the box, the pane opens et voila: you have all your options active. If you revisit your site after some time, you know that you have probably set something.

Unchecking the box should not erase the eventual options that are set, just disable them.

I know it’s not so simple to implement as it sounds, but I think it’s super neat! Especially for the Pro version that has more options still.

Cheers,

RP

De : Jeffrey Carandang [mailto:notifications@github.com]
Envoyé : mardi 21 novembre 2017 08:29
À : phpbits/widget-options <widget-options@noreply.github.com>
Cc : erpol <erpol53@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [phpbits/widget-options] On/Off switch for plugin (#33)


@erpol<https://github.com/erpol> You are very welcome! I really do appreciate your suggestions too.

I'm still confuse on the features you need though. The Enable/Disable feature is already available on Settings Widget Options and you can configure settings to select which tabs you want to enable. Let me know your thoughts. Thanks!

**Comment by phpbits** [comment]
@erpol  I can't see the image. Would you mind posting it again. Thanks!

**Comment by erpol** [comment]
Attached is the whole email with images.

RP

De : Jeffrey Carandang [mailto:notifications@github.com]
Envoyé : dimanche 26 novembre 2017 14:40
À : phpbits/widget-options <widget-options@noreply.github.com>
Cc : erpol <erpol53@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [phpbits/widget-options] On/Off switch for plugin (#33)


@erpol<https://github.com/erpol> I can't see the image. Would you mind posting it again. Thanks!

**Comment by phpbits** [comment]
Hi,

Still now showing. Would you mind going here : https://github.com/phpbits/widget-options/issues/33#issuecomment-346007109 and posting it directly on the github thread. Thanks!

**Comment by erpol** [comment]
Ok, sorry about that. 
![widget options on-off](https://user-images.githubusercontent.com/13065811/33371216-3e725622-d4fa-11e7-912f-57a466095019.jpg)
Here it is, uploaded.
RP

**Comment by phpbits** [comment]
@erpol That's a very nice option, but I'm thinking probably **Toggle Widget Options** so it will only hide the tabs and not disable the saved options. Let me think about it and survey more users. Thanks again!

**Comment by erpol** [comment]
Sure, no problem!
See what other users think, but personally I feel that unchecking and hiding the options while keeping the settings active may be misleading from the ergonomics standpoint.

RP

Le 29 nov. 2017 ? 11:57, Jeffrey Carandang <notifications@github.com<mailto:notifications@github.com>> a ?crit :


@erpol<https://github.com/erpol> That's a very nice option, but I'm thinking probably Toggle Widget Options so it will only hide the tabs and not disable the saved options. Let me think about it and survey more users. Thanks again!

-

**Comment by phpbits** [comment]
@erpol Thanks again for your feedback. Probably better to have "**Disable Widget Options**", so that it's always enabled by default and users need to check/click this option to remove the widget options on specific widget :)

**Comment by erpol** [comment]
Of course, either option works.
A survey among your installed base would be a great idea I think.

RP

Le 30 nov. 2017 ? 01:25, Jeffrey Carandang <notifications@github.com<mailto:notifications@github.com>> a ?crit :


@erpol<https://github.com/erpol> Thanks again for your feedback. Probably better to have "Disable Widget Options", so that it's always enabled by default and users need to check/click this option to remove the widget options on specific widget :)

-
