### ISSUE TITLE
Warning messages after update last version plugin

### ISSUE THREAD

**Issue by alfredo49** [phpbits/widget-options#4]
Warning: Missing argument 2 for PHPBITS_extendedWidgetsDisplay::remove_widget_title(), called in /usr/home/xxx/web/wp-includes/plugin.php on line 235 and defined in /usr/home/xxx/web/wp-content/plugins/widget-options/core/functions.widget.display.php on line 43 Warning: Missing argument 3 for PHPBITS_extendedWidgetsDisplay::remove_widget_title(), called in /usr/home/xxx/web/wp-includes/plugin.php on line 235 and defined in /usr/home/xxx/web/wp-content/plugins/widget-options/core/functions.widget.display.php on line 43 Warning: Invalid argument supplied for foreach() in /usr/home/xxx/web/wp-content/plugins/widget-options/core/functions.widget.display.php on line 46

**Comment by phpbits** [comment]
@alfredo49 are you using the latest WP version? I've updated this file with the foreach validation : https://github.com/phpbits/widget-options/blob/develop/core/functions.widget.display.php can you check if that will solve you issue. Also, what PHP version are you using? Thanks!

Cheers,
Jeffrey

**Comment by phpbits** [comment]
I've tested it again on my installations and seems to be working perfectly. Thanks!

Cheers,
Jeffrey

**Comment by alfredo49** [comment]
Yes, i use last wordpress version. It happens in all sites that the plugin
is installed

Regards

2016-11-03 13:14 GMT+01:00 Jeffrey Carandang <notifications@github.com>:

**Comment by phpbits** [comment]
@alfredo49 can you create a ticket here and include one of your site with the admin login info and will be very happy to check the issue and add the fix on the plugin : https://phpbits.net/contact/ . Thanks!

Cheers,
Jeffrey

**Comment by alfredo49** [comment]
Hi:

I use free version widget options, i dont have license key and in the form
i need it

Thxs

2016-11-03 13:17 GMT+01:00 Jeffrey Carandang <notifications@github.com>:

**Comment by phpbits** [comment]
Hi,

I think I've found the issue. Can you please replace this file again : https://github.com/phpbits/widget-options/blob/develop/core/functions.widget.display.php . Thanks!

**Comment by phpbits** [comment]
Hi @alfredo49 ,

Let me know if that fixed the issue and will push the changes on the .org repo. Thanks!

Cheers,
Jeffrey

**Comment by alfredo49** [comment]
Ok! problem is fixed!

Thxs for support

2016-11-03 13:24 GMT+01:00 Jeffrey Carandang <notifications@github.com>:

**Comment by phpbits** [comment]
No problem @alfredo49 , new plugin update will be available in a minute. Please let me know if you encounter any other issues afterwards. Thanks!

Cheers,
Jeffrey
