### ISSUE TITLE
Is there a widget that would allow a vertical list of buttons?

### ISSUE THREAD

**Issue by Grettonista** [phpbits/widget-options#40]
Something like this:
![buttons](https://user-images.githubusercontent.com/40536710/41817568-e8973b98-77e0-11e8-9d74-e07d61332b6c.jpg)

**Comment by phpbits** [comment]
Hi,

Thank you very much for the plugin interest, unfortunately this is not a plugin feature and I don't have any plugins that I can suggest for what you are looking for. Thanks again!

Cheers,
Jeffrey
