### ISSUE TITLE
PHP errors after upgrade to 3.7

### ISSUE THREAD

**Issue by jonathanstegall** [phpbits/widget-options#43]
I posted this on the WP support forums before reading the sticky posts. Figured I'd post it here as well, as it seemed like it is preferred to bring issues here.

I upgraded to version 3.7 today, and now I’m getting a number of PHP errors on every page load, whether in the admin or on the front end.

Here’s one of these errors:
```
PHP message: PHP Notice:  Undefined index: acf in /wordpress-path/wp-content/plugins/widget-options/includes/widgets/display.php on line 222
```

This happens at least ten times on each page load.

I’m not running Advanced Custom Fields at all, in case that is relevant.

**Comment by phpbits** [comment]
@jonathanstegall Thank you very much for reporting this issue. I've added the fixes here : https://github.com/phpbits/widget-options/tree/develop and would you mind replacing your files manually and let me know if the notices are gone? I'll push the updates as soon as you confirm the the issues are gone. Thank you very much!

Cheers,
Jeffrey

**Comment by jonathanstegall** [comment]
Thanks, this seems to be good now.
