### ISSUE TITLE
Error on Safari

### ISSUE THREAD

**Issue by mldunham** [phpbits/widget-options#5]
There is an error showing when I access pages in our site using the current version of Safari:

Warning: unserialize() expects parameter 1 to be string, array given in /home/content/a2pnexwpnas04_data01/07/3557007/html/wp-content/plugins/widget-options/core/functions.option.tabs.php on line 30

Warning: unserialize() expects parameter 1 to be string, array given in /home/content/a2pnexwpnas04_data01/07/3557007/html/wp-content/plugins/widget-options/core/functions.widget.display.php on line 30

I also see a flash of something similar on Chrome but it seems to clear after the first hit. This is showing at the top of the page and shows errors all over the page on older versions of safari.

**Comment by phpbits** [comment]
Hi @mldunham 

I can't seem to replicate your issue. I've added is_serialized() validation here : https://github.com/phpbits/widget-options/blob/develop/core/functions.widget.display.php can you replace your file with this and let me know if the issue were fixed and will push the update on .org repo. Thank you very much!

Cheers,
Jeffrey

**Comment by phpbits** [comment]
Hi @mldunham

Fixed on version 3.0.2 :) Feel free to update your copy and let me know when you encounter any other issues. Thanks!

Cheers,
Jeffrey
