### ISSUE TITLE
Widget page locks up

### ISSUE THREAD

**Issue by mcraftsman** [phpbits/widget-options#58]
I've been using Widget Options for awhile now. Today on a client site after upgrading to WP 5.1.1 the widget page just won't load. When I disable WO it loads fine.

Is this plugin not compatible with the latest version of WP?

Thanks,
Michelle

**Comment by nyckelplaya** [comment]
I'm also having this issue! :(

**Comment by MortezaRahmani** [comment]
Hi.
I was facing the same problem using Google Chrome + the LastPass extension.
I have checked the console on the widgets page and it was showing the below warning message for multiple times:
`[Violation] 'setTimeout' handler took 6554ms --> onloadwff.js:71`
(onloadwff.js is a JS file loaded by the LastPass extension).

So I tried disabling the LastPass and the issue was gone.
Looking for a fix...

**Comment by mcraftsman** [comment]
> Hi.
> I was facing the same problem using Google Chrome + the LastPass extension.
> I have checked the console on the widgets page and it was showing the below warning message for multiple times:
> `[Violation] 'setTimeout' handler took 6554ms --> onloadwff.js:71`
> (onloadwff.js is a JS file loaded by the LastPass extension).
> 
> So I tried disabling the LastPass and the issue was gone.
> Looking for a fix...

You're right! I opened my site in Edge without LastPass and it's working fine.  At least you found where the conflict is. Thanks for working on this. Looks like I'll have to get the PRO version!

**Comment by nyckelplaya** [comment]
@mcraftsman The pro version of which? LP or Widget Options? Does that solve anything?

Regardless, I think this needs to be re-opened. It isn't a solution for everyone to disable LastPass or use a different browser. We need a fix, not just a workaround. The [thread on wp.org](https://wordpress.org/support/topic/widget-page-locks-up/) is also dead and it's a little frustrating. 

@phpbits can you update us on whether you're going to tackle this issue? I'm ok waiting for a fix as long as it's coming eventually. If you're not going to pursue it, that's ok too. I just need to know if that's the case, so I can move on to a different solution for this functionality. I finally got most of my clients using LastPass and secure passwords. They need to be able to use their normal workflow for editing their sites. Thanks!
