### ISSUE TITLE
jQuery UI css conflicts

### ISSUE THREAD

**Issue by twiginteractive** [phpbits/widget-options#6]
Hi - 

It looks like the JQUI CSS enqueued by the plugin is conflicting with some other plugins, so that buttons and other elements in the WP Admin area are affected. Would it be possible to add an option in the plugin settings to make enqueuing this UI theme optional?

Thanks

**Comment by phpbits** [comment]
Hi @twiginteractive,

Thank you very much for reporting this issue, can you please let me know which is the other plugin and will be very happy to further check and fix the issue. You can use : 

`wp_dequeue_style( 'widgetopts-jquery-ui' );`

for the meantime to remove widget option's jquery ui. Let me know how it goes. Thanks!

Cheers,
Jeffrey

**Comment by twiginteractive** [comment]
Hi @phpbits 

Thanks for the quick response and the dequeue tip.

I noticed the conflict with the Types plugins (https://wp-types.com/) - nothing terrible, just some buttons and UI elements that were being overridden by Widget Options.

Cheers!
Jonathan

**Comment by phpbits** [comment]
Hi @twiginteractive 

Thank you very much! Will let you know when the fix was uploaded. 

Cheers,
Jeffrey

**Comment by phpbits** [comment]
@twiginteractive 

Can you send me screenshot of the conflicts? I've installed : https://wordpress.org/plugins/types/ and didn't see any issues. Thanks!

Cheers,
Jeffrey

**Comment by twiginteractive** [comment]
@phpbits 

Actually it was the Views plugin part of the Toolset suite that had conflicts - when you edit or delete a View, the attached screenshots show the popups style conflicts.

Maybe Widget Options could conditionally enqueue the UI CSS only for pages controlled by WO and not other plugins?

Thanks!

**Comment by phpbits** [comment]
@twiginteractive

I don't have the full Toolset Plugin. Please create a support ticket here : http://widget-options.com/contact/ and include a link where I can download a copy. Will just use it for this testing purposes.

Also, I've added some jQuery UI fixes for DIVI on the latest Widget Options version, please let me know if you are using the latest version and still having this issue. Thanks!

Cheers,
Jeffrey

**Comment by twiginteractive** [comment]
@phpbits 

Hi - I've tested with latest WO and latest Toolset on a clean install - the CSS conflicts are still present (easiest test is just to go to Views -> New View. You can see the close icon and other stuff has been overridden)

I've put in a ticket with a link to dropbox for the Toolset components for you to use for debugging only - please delete when done.

Thanks!

**Comment by phpbits** [comment]
Hi @twiginteractive 

Can you please replace your file with the develop branch files : https://github.com/phpbits/widget-options/tree/develop and check if the issue was fixed and if the plugin works perfectly. Thank you very much!

Cheers,
Jeffrey

**Comment by twiginteractive** [comment]
Hey @phpbits -

I've replaced the plugin files with the dev branch, and the conflicts seem to be resolved for Views. 

Thanks!

**Comment by phpbits** [comment]
Hi @twiginteractive 

Sounds perfect :) Have you checked the widgets area and settings too; if working perfectly on your end too just like mine. Just like saving and front-end values. Again, thank you so much for the effort on making this plugin better and better.

Cheers!

**Comment by twiginteractive** [comment]
I checked a few options to test (hiding a widget on a certain page etc.) and everything seemed to work as expected!

**Comment by phpbits** [comment]
@twiginteractive 

Sounds perfect! Will let my other testers finished checking all plugin features and will upload the changes. Thanks again! 

Cheers!

**Comment by phpbits** [comment]
@twiginteractive 

Fixes are now uploaded :) Feel free to update your copy. Thank you very much again!

Cheers,
Jeffrey
