### ISSUE TITLE
Page Builder by SiteOrigin: Hide title is hiding the title and widget contents

### ISSUE THREAD

**Issue by Misplon** [phpbits/widget-options#69]
**What's happening:**

Using Widget Options to hide the title of a widget in Page Builder is hiding the entire widget.

**Steps to reproduce:**

* Enable Page Builder by SiteOrigin support at Settings > Widget Options.
* Add a new Classic Editor page, add an Archives widget.
* Edit the Archives widget, add any widget title.
* Within the Archives widget go to Widget Options settings and enable **Check to hide widget title**.

<img width="213" alt="widget-options-title" src="https://user-images.githubusercontent.com/789159/63586501-b646a380-c5a1-11e9-8a41-7c7bee42f7ae.png">

The result is that the title and the widget contents are hidden.

**Intermittent results:**

If unable to reproduce, please, try [this](https://www.dropbox.com/s/ybvycqnf9q1x3jg/widget-options-test.json?dl=0) exported layout which shows the problem.

Create a new classic page. Within Page Builder, go to Layouts > Import/Export to import the JSON layout.

[Related support topic on WordPress.org](https://wordpress.org/support/topic/%d0%bd%d0%b5-%d0%b2%d1%8b%d0%b2%d0%be%d0%b4%d0%b8%d1%82%d1%81%d1%8f-%d0%ba%d0%be%d0%bd%d1%82%d0%b5%d0%bd%d1%82/).

**Comment by gregpriday** [comment]
Hi @phpbits 

If you have any ideas what might have caused this problem, I'd also be happy to add a fix to Page Builder. I assume this came up after our `2.10.7` release, but I'll investigate this weekend.

Here are the changes between `2.10.6` and the current release. Do you see anything that might cause issues with your plugin?

https://github.com/siteorigin/siteorigin-panels/compare/2.10.6...2.10.9

**Comment by Misplon** [comment]
Hi @phpbits 

We've added compatibility functionality for Widget Options [here](https://github.com/siteorigin/siteorigin-panels/commit/ddbc195e8f4f2167fd8ca72c05c9529a0f4b4850). We'll release an update in the next 12hrs.

**Comment by phpbits** [comment]
@Misplon  @gregpriday My apology for late response. I'm really glad that you've released a fix on the plugin, it's been working on the previous versions and haven't checked it again yet until now. Thank you very much for providing the fixes.

**Comment by Misplon** [comment]
@phpbits No problem, thanks for replying. If you can give the functionality a quick check when possible, that'll be great. Cheers :)
