### ISSUE TITLE
Warning Message when Activated

### ISSUE THREAD

**Issue by OatSesame** [phpbits/widget-options#7]
Hi!  When I activate the plugin, I get this warning message across the top of my screen:

Warning: unserialize() expects parameter 1 to be string, array given in /home/content/p3pnexwpnas05_data01/14/2419114/html/wp-content/plugins/widget-options/core/functions.widget.display.php on line 30

I'm not sure what to do with this? Can you help?

**Comment by phpbits** [comment]
Hi @OatSesame 

I can surely help you with this issue. Can you please send the website link and admin login info using the form here : https://phpbits.net/contact/ . I can't replicate this issue on my end so I'll be needing to check it on your site. I hope this is fine with you, thank you very much!

Cheers,
Jeffrey

**Comment by OatSesame** [comment]
I see there was an error reported on Safari too that is similar. I am working off Chrome. I'm not sure I'm comfortable providing an admin login. My site is www.OatandSesame.com. I can activate the plugin now so you can see the error?

**Comment by phpbits** [comment]
Hi @OatSesame 

You can create a new admin user and delete it later. There's a similar reported issue here : https://wordpress.org/support/topic/getting-an-error-9/ and tried to replicate it on all my sites and I'm not getting similar issue. Would really be a big help on plugin development if you can share the info and I could offer you a pro discount too when all were sorted out perfectly :) Thanks!

Cheers,
Jeffrey

**Comment by phpbits** [comment]
Hi @OatSesame ,

Fixed on version 3.0.2 :) Feel free to update your copy and let me know when you encounter any other issues. Thanks!

Cheers,
Jeffrey
