### ISSUE TITLE
Conflict between Jetpack Related Posts and Widget Options

### ISSUE THREAD

**Issue by OatSesame** [phpbits/widget-options#8]
Not sure if this is a JetPack issue or Widget Options issue, but my related posts widget from Jetpack lines up incorrectly (see oatandsesame.com sidebar) when Widget Options is activated. When I deactivate it lines back up.  This only happens on my home page and not on individual posts. Any ideas?

**Comment by phpbits** [comment]
@OatSesame 

Checked the site and it seems that you have empty link inside your widget :

```
<a href="http://skl.sh/2eUZgZO">
												</a>
```

You have to remove this, not sure where it came from though. Thanks!

**Comment by OatSesame** [comment]
Thanks so much! I know what the link is for, now I just have to figure out why it would be pulling it into the widget!

**Comment by phpbits** [comment]
Sounds great @OatSesame ! Glad you've figured it out :)

Cheers!
