### ISSUE TITLE
Can't show widget on homepage only 

### ISSUE THREAD

**Issue by pommietravels** [phpbits/widget-options#9]
Hi, I am trying to show a widget on hompege only. When I choose Show on 'Checked Pages---->Home/Front' the widget doesn't appear anywhere on the site, not even the homepage. When I click 'Hide on Checked Pages---->Home/Front' it appears everywhere, including the homepage. I can't seem to get this thing to work!! The site is www.aroundtheworldin80jobs.com

**Comment by phpbits** [comment]
Hi,

Thank you very much for choosing this plugin. How about when you've used Display Logic option by adding `is_home()` ? Thanks!
